menu:
  Home: /
  Archives: /archives
  Tags: /tags
  About: /about
  Photos: /photos
  Github: https://github.com/aymfx


# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date


# Miscellaneous
favicon: /favicon.png

highlight_theme: light

language: zh-CN